//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shadrin_new
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Room_stock = new HashSet<Room_stock>();
        }
    
        public int ID { get; set; }
        public string category1 { get; set; }
    
        public virtual ICollection<Room_stock> Room_stock { get; set; }
    }
}
