//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shadrin_new
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAYSE
    {
        public int number1 { get; set; }
        public Nullable<System.DateTime> date_of_entry { get; set; }
        public Nullable<System.DateTime> departure_date { get; set; }
        public Nullable<int> days { get; set; }
    }
}
