//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shadrin_new
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Guests
    {
        public Guests()
        {
            this.Zakaz = new HashSet<Zakaz>();
        }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public int number1 { get; set; }
        public int client { get; set; }
        public DateTime? date_of_entry { get; set; }
        public DateTime? departure_date { get; set; }

        public virtual Room_stock Room_stock { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Zakaz> Zakaz { get; set; }
    }
}