//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shadrin_new
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room_stock
    {
        public Room_stock()
        {
            this.Guests = new HashSet<Guests>();
            this.Zakaz = new HashSet<Zakaz>();
        }
    
        public int number { get; set; }
        public int category2 { get; set; }
        public int floor { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Floors Floors { get; set; }
        public virtual ICollection<Guests> Guests { get; set; }
        public virtual Room_status Room_status { get; set; }
        public virtual ICollection<Zakaz> Zakaz { get; set; }
    }
}
